### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by croxis** [ivoyager/ivoyager_project_template#3]
_Cue dramatic music_

I would love to use ivoyager as the basis of a game, however I am not the brightest bulb in the box and need a bit of handholding. Godot has a reputation of a hobbyist project, which means it attracts those with all sorts of technical abilities.

A quick list that I cam up in my poking around:

- How to create a solar system from scratch
- How to make a simple game (pew pew!) [not to mention the issues with floating point physics!]
- What needs to be synchronized for multiplayer

**Comment by charliewhitfield** [comment]
Please ask over at our forum [here](https://ivoyager.dev/forum/)! I'm going to close this but post here if you can't get signed in for some reason.
